//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCertificationInfo) DeepCopyInto(out *ImageCertificationInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCertificationInfo.
func (in *ImageCertificationInfo) DeepCopy() *ImageCertificationInfo {
	if in == nil {
		return nil
	}
	out := new(ImageCertificationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageCertificationInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCertificationInfoList) DeepCopyInto(out *ImageCertificationInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageCertificationInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCertificationInfoList.
func (in *ImageCertificationInfoList) DeepCopy() *ImageCertificationInfoList {
	if in == nil {
		return nil
	}
	out := new(ImageCertificationInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageCertificationInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCertificationInfoSpec) DeepCopyInto(out *ImageCertificationInfoSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCertificationInfoSpec.
func (in *ImageCertificationInfoSpec) DeepCopy() *ImageCertificationInfoSpec {
	if in == nil {
		return nil
	}
	out := new(ImageCertificationInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCertificationInfoStatus) DeepCopyInto(out *ImageCertificationInfoStatus) {
	*out = *in
	if in.PyxisData != nil {
		in, out := &in.PyxisData, &out.PyxisData
		*out = new(PyxisData)
		(*in).DeepCopyInto(*out)
	}
	if in.PodReferences != nil {
		in, out := &in.PodReferences, &out.PodReferences
		*out = make([]PodReference, len(*in))
		copy(*out, *in)
	}
	if in.FirstSeenAt != nil {
		in, out := &in.FirstSeenAt, &out.FirstSeenAt
		*out = (*in).DeepCopy()
	}
	if in.LastSeenAt != nil {
		in, out := &in.LastSeenAt, &out.LastSeenAt
		*out = (*in).DeepCopy()
	}
	if in.LastPyxisCheckAt != nil {
		in, out := &in.LastPyxisCheckAt, &out.LastPyxisCheckAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DaysUntilEOL != nil {
		in, out := &in.DaysUntilEOL, &out.DaysUntilEOL
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCertificationInfoStatus.
func (in *ImageCertificationInfoStatus) DeepCopy() *ImageCertificationInfoStatus {
	if in == nil {
		return nil
	}
	out := new(ImageCertificationInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodReference) DeepCopyInto(out *PodReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodReference.
func (in *PodReference) DeepCopy() *PodReference {
	if in == nil {
		return nil
	}
	out := new(PodReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyxisData) DeepCopyInto(out *PyxisData) {
	*out = *in
	if in.PublishedAt != nil {
		in, out := &in.PublishedAt, &out.PublishedAt
		*out = (*in).DeepCopy()
	}
	if in.Vulnerabilities != nil {
		in, out := &in.Vulnerabilities, &out.Vulnerabilities
		*out = new(VulnerabilitySummary)
		**out = **in
	}
	if in.EOLDate != nil {
		in, out := &in.EOLDate, &out.EOLDate
		*out = (*in).DeepCopy()
	}
	if in.Architectures != nil {
		in, out := &in.Architectures, &out.Architectures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ArchitectureHealth != nil {
		in, out := &in.ArchitectureHealth, &out.ArchitectureHealth
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdvisoryIDs != nil {
		in, out := &in.AdvisoryIDs, &out.AdvisoryIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyxisData.
func (in *PyxisData) DeepCopy() *PyxisData {
	if in == nil {
		return nil
	}
	out := new(PyxisData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VulnerabilitySummary) DeepCopyInto(out *VulnerabilitySummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VulnerabilitySummary.
func (in *VulnerabilitySummary) DeepCopy() *VulnerabilitySummary {
	if in == nil {
		return nil
	}
	out := new(VulnerabilitySummary)
	in.DeepCopyInto(out)
	return out
}
